[package]
name = "rust-mailer"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]

[dependencies]
futures = "*"
futures-cpupool = "*"
tokio-core = "*"
tokio-service = "*"
tokio-proto = "*"
